/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio1;

import java.awt.ComponentOrientation;
import javafx.scene.control.ComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author mvarela6
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    double v[];

    public principal() {
        initComponents();
        cmdcalcular.setEnabled(false);
        cmdllenadoautomatico.setEnabled(false);
        cmdllenadomanual.setEnabled(false);
        cmdborrar.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtlongitud = new javax.swing.JTextField();
        cmboperaciones = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        cmdcrear = new javax.swing.JButton();
        cmdllenadomanual = new javax.swing.JButton();
        cmdllenadoautomatico = new javax.swing.JButton();
        cmdcalcular = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtresultado = new javax.swing.JTextArea();
        cmdborrar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtresultado2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("OPERACIONES CON VECTORES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 200, 30));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos inicailes"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Longuitud:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 70, 20));

        txtlongitud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtlongitudKeyTyped(evt);
            }
        });
        jPanel2.add(txtlongitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 120, 40));

        cmboperaciones.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Suma", "Productoria", "Mayor Elemento", "Menor ELemento", " " }));
        cmboperaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmboperacionesActionPerformed(evt);
            }
        });
        jPanel2.add(cmboperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 170, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 220, 140));
        jPanel2.getAccessibleContext().setAccessibleName("");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdcrear.setText("Crear");
        cmdcrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdcrearActionPerformed(evt);
            }
        });
        jPanel3.add(cmdcrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 140, 40));

        cmdllenadomanual.setText("Llenado Manual");
        cmdllenadomanual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdllenadomanualActionPerformed(evt);
            }
        });
        cmdllenadomanual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cmdllenadomanualKeyTyped(evt);
            }
        });
        jPanel3.add(cmdllenadomanual, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, 40));

        cmdllenadoautomatico.setText("Llenado automatico");
        cmdllenadoautomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdllenadoautomaticoActionPerformed(evt);
            }
        });
        jPanel3.add(cmdllenadoautomatico, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 140, 40));

        cmdcalcular.setText("Calcular");
        cmdcalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdcalcularActionPerformed(evt);
            }
        });
        jPanel3.add(cmdcalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 140, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 180, 270));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtresultado.setColumns(20);
        txtresultado.setRows(5);
        jScrollPane1.setViewportView(txtresultado);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 220, 100));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 250, 140));

        cmdborrar.setText("Borrar");
        cmdborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdborrarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdborrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 100, 40));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado Vectores:"));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtresultado2.setColumns(20);
        txtresultado2.setRows(5);
        jScrollPane2.setViewportView(txtresultado2);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 220, 90));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 250, 120));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmboperacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmboperacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmboperacionesActionPerformed

    private void cmdcrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdcrearActionPerformed
        int longitud;

        if (txtlongitud.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite la longuitud", "Error", JOptionPane.ERROR_MESSAGE);
            txtlongitud.requestFocusInWindow();
        } else if (Integer.parseInt(txtlongitud.getText().trim()) == 0) {
            JOptionPane.showMessageDialog(this, "La longitud debe ser mayor que cero", "Error", JOptionPane.ERROR_MESSAGE);
            txtlongitud.requestFocusInWindow();
            txtlongitud.selectAll();
        } else {
            longitud = Integer.parseInt(txtlongitud.getText());
            v = new double[longitud];
            JOptionPane.showMessageDialog(this, "Vector creado correctamente!");

            cmdcrear.setEnabled(false);
            cmdllenadomanual.setEnabled(true);
            cmdllenadoautomatico.setEnabled(true);
            cmdborrar.setEnabled(true);
            txtlongitud.setEnabled(false);
            cmdcalcular.setEnabled(false);

        }


    }//GEN-LAST:event_cmdcrearActionPerformed

    private void txtlongitudKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlongitudKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtlongitudKeyTyped

    private void cmdllenadomanualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdllenadomanualActionPerformed
        double n;
        for (int i = 0; i < v.length; i++) {
            n = Double.parseDouble(JOptionPane.showInputDialog(this, "Digite el elemento en la posición: " + i));
            v[i] = n;
        } 
        for (int i = 0; i <v.length; i++) {
            txtresultado2.append(v[i] + "\n");
        }
        cmdcrear.setEnabled(false);
        cmdllenadomanual.setEnabled(false);
        cmdllenadoautomatico.setEnabled(false);
        cmdcalcular.setEnabled(true);
        cmdborrar.setEnabled(true);
        txtlongitud.setEditable(false);


    }//GEN-LAST:event_cmdllenadomanualActionPerformed

    private void cmdllenadoautomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdllenadoautomaticoActionPerformed
        int n;
        for (int i = 0; i < v.length; i++) {
            n = (int) (Math.random() * 25 + 1);
            v[i] = n;
        }
        for (int i = 0; i <v.length; i++) {
            txtresultado2.append(v[i] + "\n");
        }
        JOptionPane.showMessageDialog(this, "Vector creado correctamente");

        cmdcrear.setEnabled(false);
        cmdllenadomanual.setEnabled(false);
        cmdllenadoautomatico.setEnabled(false);
        cmdcalcular.setEnabled(true);
        cmdborrar.setEnabled(true);
        txtlongitud.setEditable(false);
    }//GEN-LAST:event_cmdllenadoautomaticoActionPerformed

    private void cmdborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdborrarActionPerformed

        txtresultado.setText("");
        txtlongitud.setText("");
        txtlongitud.requestFocusInWindow();
        v = null;
        cmdcrear.setEnabled(true);
        cmdllenadomanual.setEnabled(false);
        cmdllenadoautomatico.setEnabled(false);
        cmdcalcular.setEnabled(false);
        cmdborrar.setEnabled(true);
        txtlongitud.setEnabled(true);
        txtlongitud.setEditable(true);
    }//GEN-LAST:event_cmdborrarActionPerformed

    private void cmdcalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdcalcularActionPerformed

        if (txtlongitud.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite la longitud del vector", "Error", JOptionPane.ERROR_MESSAGE);
            txtlongitud.requestFocusInWindow();
        } else if (Integer.parseInt(txtlongitud.getText().trim()) == 0) {
            JOptionPane.showMessageDialog(this, "La longitud debe ser mayor que cero", "Error", JOptionPane.ERROR_MESSAGE);
            txtlongitud.requestFocusInWindow();
            txtlongitud.selectAll();
        } else {

            int longitud, opc;
            double sumatoria = 0, productoria = 1, mayor = 0, menor = 0;
            longitud = Integer.parseInt(txtlongitud.getText());
            opc = cmboperaciones.getSelectedIndex();

            switch (opc) {
                case 0:
                    for (int i = 0; i < v.length; i++) {
                        sumatoria = v[i] + sumatoria;
                    }
                    txtresultado.setText(sumatoria + "");
                    break;

                case 1:
                    for (int i = 0; i < v.length; i++) {
                        productoria = v[i] * productoria;
                    }
                    txtresultado.setText(productoria + "");
                    break;

                case 2:
                    for (int i = 0; i < v.length; i++) {
                        if (i == 0) {
                            mayor = v[0];
                            menor = v[0];
                        }

                        if (v[i] > mayor) {
                            mayor = v[i];
                        }
                    }
                    txtresultado.setText(mayor + "");
                    break;

                case 3:
                    for (int i = 0; i < v.length; i++) {
                        if (i == 0) {
                            mayor = v[0];
                            menor = v[0];
                        }

                        if (v[i] < menor) {
                            menor = v[i];
                        }
                    }
                    txtresultado.setText(menor + "");
                    break;
            }

        }
    }//GEN-LAST:event_cmdcalcularActionPerformed

    private void cmdllenadomanualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmdllenadomanualKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_cmdllenadomanualKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmboperaciones;
    private javax.swing.JButton cmdborrar;
    private javax.swing.JButton cmdcalcular;
    private javax.swing.JButton cmdcrear;
    private javax.swing.JButton cmdllenadoautomatico;
    private javax.swing.JButton cmdllenadomanual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtlongitud;
    private javax.swing.JTextArea txtresultado;
    private javax.swing.JTextArea txtresultado2;
    // End of variables declaration//GEN-END:variables
}
